Driver Service: Entities, migration, dto, mappers
dulfinne/taxi-api pull request #6
Opened 2024-11-04 12:15 UTC by dulfinne

2024-11-04 16:23 UTC, aleshkey requested changes

2024-11-04 16:23 UTC, aleshkey commented on driver-service/pom.xml
> +            <version>1.5.5.Final</version>
версию в properties

2024-11-04 16:23 UTC, aleshkey commented on driver-service/src/main/java/com/dulfinne/taxi/driverservice/dto/request/CarRequest.java
> +    @NotNull(message = "Please enter registration number")
Сообщения вынеси в константы - так, чтобы их можно было локализовать
Есть два варианта:

Возвращать сразу локализованное сообщение (на русском, английском, любом другом языке) в зависимости от переданных хэдеров в запросе
Возвращать только ключ, а не само сообщение и тогда фронт сам подставит сообщение и локализует его

https://github.com/zowe/sample-spring-boot-api-service/blob/master/zowe-rest-api-sample-spring/docs/i18n.md

2024-11-04 16:23 UTC, aleshkey commented on driver-service/src/main/java/com/dulfinne/taxi/driverservice/model/CarClass.java
> +public enum CarClass {
Лучше переименовать название класса

2024-11-04 16:23 UTC, aleshkey commented on driver-service/pom.xml
> +    <url/>
ненужные теги можно убрать

2024-11-04 16:23 UTC, aleshkey commented on driver-service/src/main/java/com/dulfinne/taxi/driverservice/model/DriverInfo.java
> +public class DriverInfo {
Есть просто Car, а тут DriverInfo. Почему не просто Driver?

2024-11-05 08:25 UTC, aleshkey requested changes

2024-11-05 08:25 UTC, aleshkey commented on driver-service/pom.xml
> +            <version>1.5.5.Final</version>
тут нужно написать <version>${mapstruct.version}</version>, т.е. сделать как с ломбоком

2024-11-05 08:25 UTC, aleshkey commented on driver-service/src/main/java/com/dulfinne/taxi/driverservice/controller/DriverController.java
> +public class DriverController {
это точно относится к этому ПР?

2024-11-05 08:25 UTC, aleshkey commented on driver-service/src/main/java/com/dulfinne/taxi/driverservice/dto/request/CarRequest.java
> +            regexp = "\\d{4}[A-Z]{2}-[1-7]",
тоже лучше вынести в константы

2024-11-05 08:25 UTC, aleshkey commented on driver-service/src/main/java/com/dulfinne/taxi/driverservice/exception/GlobalExceptionHandler.java
> +public class GlobalExceptionHandler {
тоже точно к этому ПР относится?

2024-11-05 08:26 UTC, dulfinne commented on driver-service/src/main/java/com/dulfinne/taxi/driverservice/exception/GlobalExceptionHandler.java
> +public class GlobalExceptionHandler {
делала для проверки, забыла удалить

2024-11-05 08:58 UTC, aleshkey approved these changes

2024-11-05 09:32 UTC, merged